export const homepage = {
  hero: {
    eyebrow: "Connected growth systems for ambitious service businesses",
    headline: "Make revenue growth more predictable.",
    body: "Stonehurst Lane connects websites, paid acquisition, search, CRM and follow-up into one measurable system designed to generate, qualify and move better opportunities.",
  },
  recognition: {
    eyebrow: "Recognition",
    headline: "Growth is rarely broken in only one place.",
    body: "Most operators do not have a marketing problem or a sales problem. They have a system problem — small breakages across acquisition, conversion, follow-up and reporting that quietly compound.",
    symptoms: [
      "Ads generate clicks but the website does not convert.",
      "Leads arrive but follow-up is inconsistent.",
      "Marketing activity cannot be connected to revenue.",
      "Salespeople spend time on poor-fit enquiries.",
      "Different providers manage disconnected parts of the journey.",
      "Growth still depends heavily on referrals or the founder.",
    ],
  },
  system: {
    eyebrow: "The connected growth system",
    headline: "From attention to revenue, engineered as one system.",
    body: "Every capability we operate sits on the same commercial pipeline. Traffic is only useful if it becomes an enquiry. Enquiries are only useful if they become qualified opportunities. Opportunities are only useful if they become revenue.",
    stages: [
      { name: "Attention", body: "Meta, Google, SEO, referrals and content." },
      { name: "Consideration", body: "Website architecture and offer design." },
      { name: "Enquiry", body: "Forms, calls and inbound routing." },
      { name: "Qualification", body: "Lead scoring, intake and triage." },
      { name: "Follow-up", body: "Automation, sequences and human touch." },
      { name: "Opportunity", body: "Sales pipeline, consultation and proposal." },
      { name: "Revenue", body: "Reporting, retention and reallocation." },
    ],
  },
  whyFullStack: {
    eyebrow: "Why full-stack",
    headline: "Why Stonehurst Lane runs the full stack.",
    body: "Isolated channel work underperforms because each piece assumes the others are working. We do not accept that assumption.",
    points: [
      "We do not send paid traffic to pages that cannot convert.",
      "We do not build websites without considering acquisition.",
      "We do not generate leads without considering follow-up.",
      "We do not report vanity metrics without connecting them to a commercial objective.",
      "We do not recommend every service when one bottleneck should be fixed first.",
    ],
  },
  process: {
    eyebrow: "Engagement process",
    headline: "How we work.",
    stages: [
      { number: "01", name: "Diagnose", body: "Growth Systems Audit against the whole pipeline." },
      { number: "02", name: "Prioritise", body: "Fix the constraint before the symptoms." },
      { number: "03", name: "Design", body: "System, offer and measurement designed together." },
      { number: "04", name: "Build", body: "Sites, campaigns and infrastructure engineered to spec." },
      { number: "05", name: "Launch", body: "Coordinated launch across every layer." },
      { number: "06", name: "Measure", body: "Reporting tied to pipeline and revenue." },
      { number: "07", name: "Improve", body: "Reallocation based on evidence, not opinion." },
    ],
  },
  offer: {
    eyebrow: "Founding Growth Partner",
    headline: "A selective founding-partner arrangement.",
    body: "For a limited number of serious partners, Stonehurst Lane offers a reduced-risk entry into the full growth system.",
    items: [
      "$100 first-month campaign management",
      "Conversion-focused website included",
      "Three months of foundational SEO included",
      "Founding-partner ongoing SEO rate",
      "Defined management-fee fallback where initial qualifying results are not achieved",
      "CRM and pipeline foundation",
      "Growth Systems Audit",
    ],
    clarifications: [
      "Qualification applies.",
      "Advertising spend is separate.",
      "Software and third-party costs are separate.",
      "Website and SEO scope is defined in the engagement agreement.",
      "The arrangement is not intended for businesses seeking only free services.",
    ],
  },
  application: {
    eyebrow: "Application",
    headline: "Find where your growth system is losing opportunity.",
    body: "Tell us about the business, current marketing and primary constraint. Stonehurst Lane will identify the most useful place to begin.",
  },
};
