export const validLeadStartPayload = {
  sessionId: "d9428888-122b-4c5f-a5a8-f34421d07c92",
  firstName: "Jordan",
  organisationName: "Harbour Podiatry",
  email: "jordan@example.com",
  phone: "+61 400 000 000",
  campaignId: "podiatry-clinics",
  industryId: "allied-health",
  firstLandingPage: "https://stonehurstlane.com/growth-partners/podiatry-clinics",
  currentLandingPage: "https://stonehurstlane.com/growth-partners/podiatry-clinics",
  referrer: "https://www.google.com/",
  utmSource: "google",
  utmMedium: "cpc",
  utmCampaign: "podiatry-sydney",
  utmContent: "clinic-growth",
  utmTerm: "podiatry marketing",
  fbclid: "test-fbclid",
  ctaLocation: "hero",
  privacyConsent: true as const,
};
