alter table public.leads
  add column practitioner_range text,
  add column location_range text,
  add column capacity_status text,
  add column acquisition_source text,
  add column website_url text,
  add column decision_authority text,
  add column google_ads_status text,
  add column planned_ad_spend_range text,
  add column implementation_timing text,
  add column website_status text,
  add column primary_growth_problem text,
  add column additional_context text,
  add column next_action text,
  add column callback_preference text,
  add column callback_requested_at timestamptz,
  add column qualification_completed_at timestamptz,
  add column funnel_completed_at timestamptz,
  add column cal_booking_status text,
  add column cal_booking_uid text,
  add column cal_booking_url text,
  add column cal_booking_start_at timestamptz,
  add column cal_booking_timezone text,
  add column cal_booking_created_at timestamptz,
  add column cal_booking_cancelled_at timestamptz,
  add column cal_webhook_received_at timestamptz,
  add constraint leads_practitioner_range_check check (practitioner_range is null or practitioner_range in ('solo', '2-3', '4-6', '7-10', '11+')),
  add constraint leads_location_range_check check (location_range is null or location_range in ('1', '2', '3', '4+')),
  add constraint leads_capacity_status_check check (capacity_status is null or capacity_status in ('need-now', 'some', 'near-capacity', 'unsure')),
  add constraint leads_acquisition_source_check check (acquisition_source is null or acquisition_source in ('referrals', 'organic-google', 'google-ads', 'meta-ads', 'partnerships', 'other')),
  add constraint leads_decision_authority_check check (decision_authority is null or decision_authority in ('owner', 'part-decision', 'researching')),
  add constraint leads_google_ads_status_check check (google_ads_status is null or google_ads_status in ('current', 'previous', 'never', 'unsure')),
  add constraint leads_planned_ad_spend_range_check check (planned_ad_spend_range is null or planned_ad_spend_range in ('under-1000', '1000-1500', '1500-3000', '3000+', 'unsure')),
  add constraint leads_implementation_timing_check check (implementation_timing is null or implementation_timing in ('immediately', '30-days', '1-3-months', 'later')),
  add constraint leads_website_status_check check (website_status is null or website_status in ('performing', 'needs-improvement', 'need-new', 'none', 'unsure')),
  add constraint leads_primary_growth_problem_check check (primary_growth_problem is null or primary_growth_problem in ('referral-reliance', 'inconsistent-enquiries', 'ads-underperforming', 'website-not-converting', 'poor-quality-leads', 'limited-tracking', 'other')),
  add constraint leads_next_action_check check (next_action is null or next_action in ('booking', 'callback')),
  add constraint leads_callback_preference_check check (callback_preference is null or callback_preference in ('morning', 'afternoon', 'no-preference')),
  add constraint leads_cal_booking_status_check check (cal_booking_status is null or cal_booking_status in ('opened', 'client-reported', 'created', 'rescheduled', 'cancelled')),
  add constraint leads_website_url_length check (website_url is null or char_length(website_url) <= 2048),
  add constraint leads_website_url_protocol check (website_url is null or website_url ~* '^https?://'),
  add constraint leads_additional_context_length check (additional_context is null or char_length(additional_context) <= 1000),
  add constraint leads_cal_booking_uid_length check (cal_booking_uid is null or char_length(cal_booking_uid) <= 255),
  add constraint leads_cal_booking_url_length check (cal_booking_url is null or char_length(cal_booking_url) <= 2048),
  add constraint leads_cal_booking_url_protocol check (cal_booking_url is null or cal_booking_url ~* '^https://'),
  add constraint leads_cal_booking_timezone_length check (cal_booking_timezone is null or char_length(cal_booking_timezone) <= 100),
  add constraint leads_callback_consistency check (callback_requested_at is null or next_action = 'callback'),
  add constraint leads_cal_created_consistency check (cal_booking_created_at is null or cal_booking_uid is not null),
  add constraint leads_cal_cancelled_consistency check (cal_booking_cancelled_at is null or cal_booking_status = 'cancelled');

create index leads_cal_booking_uid_idx on public.leads (cal_booking_uid) where cal_booking_uid is not null;

grant update (
  practitioner_range, location_range, capacity_status, acquisition_source, website_url,
  decision_authority, google_ads_status, planned_ad_spend_range, implementation_timing,
  website_status, primary_growth_problem, additional_context, next_action,
  callback_preference, callback_requested_at, qualification_completed_at,
  funnel_completed_at, cal_booking_status, cal_booking_uid, cal_booking_url,
  cal_booking_start_at, cal_booking_timezone, cal_booking_created_at,
  cal_booking_cancelled_at, cal_webhook_received_at
) on table public.leads to service_role;
